# Build Hugo site and deploy to Infomaniak
name: Deploy Hugo site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "deploy"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.145.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "https://yossi.eu/"

      - name: Deploy to Infomaniak
        env:
          SSHPASS: ${{ secrets.PASSWORD }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -e sftp -o StrictHostKeyChecking=no -o Port=22 JLn6voVHQsM_github@57-107586.ssh.hosting-ik.com << 'SFTP'
          cd /srv/customer/sites/yossi.eu
          pwd
          bye
          SFTP
